[0m14:59:38.936495 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x102ca5610>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105f33650>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105f333e0>]}


============================== 14:59:38.939859 | 7278371a-6cfc-4444-bcd8-93eb978b07a8 ==============================
[0m14:59:38.939859 [info ] [MainThread]: Running with dbt=1.9.2
[0m14:59:38.940221 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'profiles_dir': './dbt/profiles', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'invocation_command': 'dbt run', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m14:59:38.940553 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/timofejvila/Desktop/ELT2/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m14:59:38.941642 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.046038084, "process_in_blocks": "0", "process_kernel_time": 0.16068, "process_mem_max_rss": "99450880", "process_out_blocks": "0", "process_user_time": 0.779176}
[0m14:59:38.941911 [debug] [MainThread]: Command `dbt run` failed at 14:59:38.941861 after 0.05 seconds
[0m14:59:38.942116 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105ee0e60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105cfce60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105f335f0>]}
[0m14:59:38.942291 [debug] [MainThread]: Flushing usage events
[0m14:59:39.643984 [debug] [MainThread]: An error was encountered while trying to flush usage events
